openapi: 3.0.4
info: 
  title: hohohost api
  version: v1
paths:
  /wish:
      get: 
        description: returns the wish list of the user
        responses:
          200: 
            description: successfully get the wish
            content:
              application/json: 
                schema: 
                  type: array
                  items:
                    $ref: "#/components/schemas/Wish"
      post:
        description: create new wish
        responses:
          201:
            description: successfully create new wish
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Wish"
        requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateWishRequest"

  /wish/{wishId}:
    get: 
      description: returns a wish
      parameters:
        - name: wishId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200: 
          description: successfully get the wish
          content:
            application/json: 
              schema: 
                $ref: "#/components/schemas/Wish"
    put:
      description: updates an existing wish
      parameters:
        - name: wishId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successfully update the wish
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wish"
  
              

components:
  schemas:
    Wish:
      type: object
      required:
        - id
        - userId
        - giftName
        - price
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        giftName:
          type: string
        price:
          type: number
          format: float
        url:
          type: string
          format: uri
    CreateWishRequest:
      type: object
      required:
        - userId
        - giftName
        - price
      properties:
        userId:
          type: string
          format: uuid
        giftName:
          type: string
        price:
          type: number
          format: float
        url:
          type: string
          format: uri