openapi: 3.0.4
info: 
  title: hohohost api
  version: v1
paths:
  /wish:
      get: 
        description: returns the wish list of the user
        responses:
          200: 
            description: successfully get the wish
            content:
              application/json: 
                schema: 
                  type: array
                  items:
                    $ref: "#/components/schemas/Wish"
      post:
        description: create new wish
        responses:
          201:
            description: successfully create new wish
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Wish"
        requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateWishRequest"

  /wish/{wishId}:
    get: 
      description: returns a wish
      parameters:
        - name: wishId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200: 
          description: successfully get the wish
          content:
            application/json: 
              schema: 
                $ref: "#/components/schemas/Wish"
    put:
      description: updates an existing wish
      parameters:
        - name: wishId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successfully updates the wish
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wish"
    delete:
      description: deletes an existing wish
      parameters:
        - name: wishId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successfully deletes the wish
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wish"
  /user:
    post:
      description: creates a new user
      responses:
        200:
          description: successfully creates the new user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateUserRequest"

  /user/{userId}:
    get:
      description: returns the user detail
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successfully returns the user detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    put:
      description: updates user detail
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successfully updates the user detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

  /group:
    post:
      description: creates a new group
      responses:
        200:
          description: successfully creates a new group
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateGroupRequest"

  /group/{groupId}:
    get:
      description: returns the group detail
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successfully returns the group detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
    put:
      description: updates the group detail
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successfully updates the group detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
      
  /santa:
    post:
      description: creates a new secret santa
      responses:
        200:
          description: successfully creates a new secret santa
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateSantaRequest"
  /santa/{santaId}:
    get:
      description: returns the secret santa detail
      parameters:
        - name: santaId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successfully returns the secret santa detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Santa"

components:
  schemas:
    Wish:
      type: object
      required:
        - id
        - userId
        - giftName
        - price
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        giftName:
          type: string
        price:
          type: number
          format: float
        url:
          type: string
          format: uri
    CreateWishRequest:
      type: object
      required:
        - userId
        - giftName
        - price
      properties:
        userId:
          type: string
          format: uuid
        giftName:
          type: string
        price:
          type: number
          format: float
        url:
          type: string
          format: uri
    User:
      type: object
      required:
        - id
        - firstName
        - lastName
        - email
        - password
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
            type: string
    CreateUserRequest:
      type: object
      required:
        - firstName
        - lastName
        - email
        - password
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
    Group:
      type: object
      required:
        - id
        - groupName
        - priceLimit
      properties:
        id:
          type: string
          format: uuid
        groupName:
          type: string
        priceLimit:
          type: integer
    CreateGroupRequest:
      type: object
      required:
        - groupName
        - priceLimit
      properties:
        groupName:
          type: string
        priceLimit:
          type: integer
    Santa:
      type: object
      required:
        - id
        - groupId
        - giverId
        - receiverId
      properties:
        id:
          type: string
          format: uuid
        groupId:
          type: string
          format: uuid
        giverId:
          type: string
          format: uuid
        receiverId:
          type: string
          format: uuid
    CreateSantaRequest:
      type: object
      required:
        - groupId
        - giverId
        - receiverId
      properties:
        groupId:
          type: string
          format: uuid
        giverId:
          type: string
          format: uuid
        receiverId:
          type: string
          format: uuid
  